print("I feel sick:(")
print("I still feel sick:/")
print("Still sick but maybe a bit better man this really sucks:c")
print("Yesterday I was still sick and today I am too but I feel somewhat better and I can think now, this caugh sucks tho")
print("Still smh")
print("how stillll")
print("ughhh still sick")
print("Still this is insane")