print("I feel sick:(")
print("I still feel sick:/")
print("Still sick but maybe a bit better man this really sucks:c")
print("Yesterday I was still sick and today I am too but I feel somewhat better and I can think now, this caugh sucks tho")
print("Still smh")
print("how stillll")
print("ughhh still sick")
print("Still this is insane")
print("starting to feel better")
print("nose nose nose")
print("mostly better but there's sm to do rn")
print("doing this till saturday")
print("god I hope this is the last day")
print("second to last day for sure")
print("done!")
print("hi")

